### ISSUE TITLE
Can't see groups from Kubernetes

### ISSUE THREAD

**Issue by pablokbs** [jetstack/okta-kubectl-auth#12]
Hello @simonswine ! Thanks for writing this tool. For some reason I can't see the groups on the Kubernetes side from okta, I've double check the configuration following your docs and everything looks fine. I've tested the response from Okta and I see the groups in there:

<img width="569" alt="Captura de Pantalla 2020-01-16 a la(s) 17 26 57" src="https://user-images.githubusercontent.com/4028336/72560274-78feed00-3885-11ea-9f93-890c9b06c175.png">

But when I try to run a kubectl command, the groups are not present:

`kube-apiserver-ip-10-80-24-218.ec2.internal kube-apiserver I0116 20:11:31.023926       1 rbac.go:118] RBAC DENY: user "okta:pablo@example.com" groups ["system:authenticated"] cannot "list" resource "pods" in namespace "default"`

If I create a clusterrolebinding using `okta:pablo@example.com` it works fine, but if I want to use a Group, it doesn't work. This makes sense, as Kubernetes can't see the groups I belong to:

```
# cluster-role.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: managers
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
apiVersion: rbac.authorization.k8s.io/v1
```

```
# cluster-rolebinding-user.yaml
# This works fine

kind: ClusterRoleBinding
metadata:
  name: okta-pablo
subjects:
- kind: User
  name: okta:pablo@example.com
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: managers
  apiGroup: ""apiVersion: rbac.authorization.k8s.io/v1
```

```
# cluster-rolebinding-group.yaml
# this doesn't work

kind: ClusterRoleBinding
metadata:
  name: okta-sre
subjects:
- kind: Group
  name: okta:SRE
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: managers
  apiGroup: ""
```

Could it be related to #3 ?
